name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install and Build
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev python3-dev \
          libssl-dev git zip unzip openjdk-17-jdk zlib1g-dev \
          autoconf libtool pkg-config libncurses5-dev libncursesw5-dev \
          libtinfo6 cmake libsqlite3-dev
          pip install --upgrade pip
          pip install Cython==0.29.33 buildozer
          # Cette ligne lance la cr√©ation de l'APK
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MonApplication-APK
          path: bin/*.apk
